<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'e2bbaaa24339f6d842bea037ca346cee',
  'DATABASE_URL' => 'mysql://user:111@127.0.0.1:3306/kolo?serverVersion=5.7',
);
